ProjektFinish
Moni73/KunstStuebchen-Capstone pull request #6
Opened 2022-05-24 20:43 UTC by Moni73

2022-05-24 21:09 UTC, AlexF090 requested changes
Hope you find my small comments helpful.

2022-05-24 21:09 UTC, AlexF090 commented on client/src/pages/projekt/projekt.css
> +  padding: 14px;
Maybe it is better to use the unit em instead of px at this point.

2022-05-24 21:09 UTC, AlexF090 commented on client/src/pages/projekt/projekt.css
> +  padding: 16px;
Same here

2022-05-24 21:09 UTC, AlexF090 commented on client/src/pages/projekt/projekt.css
> +  padding: 18px;
Same here 😊

2022-05-24 21:09 UTC, AlexF090 commented on client/src/pages/projekt/projekt.css
> +  font-size: 36px;
At this point I would have recommended you to use rem instead of px. 😊

2022-05-24 21:09 UTC, AlexF090 commented on client/src/pages/projekt/projekt.css
> +  padding: 18px;
(em)

2022-05-24 21:09 UTC, AlexF090 commented on client/src/pages/projekt/projekt.css
> +  font-size: 32px;
At this point I would have recommended you to use rem instead of px. 😊

2022-05-25 09:08 UTC, Moni73 commented on api/.env
> +API_KEY=636446719397937
Thanks Alex !

2022-05-25 09:08 UTC, merged